In [29]:
import numpy as np

arr1 = np.array((1, 2, 3, 4))
arr2 = np.arange(2, 6) # создание массива от 2 до 6 не включительно
arr3 = np.zeros((2, 3)) # создане массива 2х3 из нулей 
arr4 = np.linspace(2, 3, 10) # создание массива из десяти чисел от 2 до 3
arr5 = np.ones((1)) # одномерный массив из единиц
arr6 = np.array([7, 6, 5, 4]) # создание массива из обычного списка
temp = [0, 9, 8, 7]
arr7 = np.array(temp) # создание массива из обычного списка

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)

[1 2 3 4]
[2 3 4 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
 2.66666667 2.77777778 2.88888889 3.        ]
[1.]
[7 6 5 4]
[0 9 8 7]


In [49]:
print(arr4.shape) # размерность массива
print(arr1.dtype) # тип элементов массива
print(arr4.dtype)

(10,)
int64
float64


In [41]:
print(arr2[2]) # вывод элемента с индексом 2
print(arr1[1:3]) # срез с 1-го до 3-го элемента не включительно

4
[2 3]


In [45]:
print(arr1 + arr2) # поэлементное сложение
print(arr1 * arr2) # поэлементное умножение

[3 5 7 9]
[ 2  6 12 20]


In [47]:
print(arr2.mean()) # среднее арифметическое

3.5
